# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171022_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xbe\xd1\x81\xd1\x82\xd0\xb5\xd1\x80\xd0\xb0')),
                ('image', models.ImageField(upload_to=b'images/slider', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x80\xd1\x82\xd0\xb8\xd0\xbd\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xbe\xd1\x81\xd1\x82\xd0\xb5\xd1\x80\xd0\xb0')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0442\u0435\u0440',
                'verbose_name_plural': '\u041f\u043e\u0441\u0442\u0435\u0440\u044b',
            },
        ),
    ]
