# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171031_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xbe\xd1\x81\xd1\x82\xd0\xb5\xd1\x80\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xbe\xd1\x81\xd1\x82\xd0\xb5\xd1\x80\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_tr',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xbf\xd0\xbe\xd1\x81\xd1\x82\xd0\xb5\xd1\x80\xd0\xb0'),
        ),
    ]
