# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171031_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=b'files/news', verbose_name=b'\xd1\x84\xd0\xb0\xd0\xb9\xd0\xbb \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xba\xd0\xb0\xd1\x87\xd0\xb8\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f (Any Files)'),
        ),
        migrations.AddField(
            model_name='news',
            name='files_en',
            field=models.FileField(blank=True, null=True, upload_to=b'files/news', verbose_name=b'\xd1\x84\xd0\xb0\xd0\xb9\xd0\xbb \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xba\xd0\xb0\xd1\x87\xd0\xb8\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f (Any Files)'),
        ),
        migrations.AddField(
            model_name='news',
            name='files_tr',
            field=models.FileField(blank=True, null=True, upload_to=b'files/news', verbose_name=b'\xd1\x84\xd0\xb0\xd0\xb9\xd0\xbb \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x81\xd0\xba\xd0\xb0\xd1\x87\xd0\xb8\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f (Any Files)'),
        ),
    ]
