# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171101_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
