# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20171101_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd1\x8b')),
                ('image', models.ImageField(upload_to=b'images/countries', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x80\xd1\x82\xd0\xb0 \xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd1\x8b')),
            ],
            options={
                'verbose_name': '\u043e\u0431\u044a\u0435\u043a\u0442',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0443\u043d\u0438\u0432\u0435\u0440\u0441\u0438\u0442\u0435\u0442\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='university',
            name='mode',
            field=models.CharField(choices=[(b'kurucu', b'Kurucu Uye'), (b'tum', b'Tum uye')], default=1, max_length=20, verbose_name=b'\xd0\x92\xd1\x8b\xd0\xb1\xd0\xb5\xd1\x80\xd0\xb8\xd1\x82\xd0\xb5 \xd1\x82\xd0\xb8\xd0\xbf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainuniversity',
            name='university',
            field=models.ManyToManyField(max_length=20, to='main.University', verbose_name=b'\xd0\x92\xd1\x8b\xd0\xb1\xd0\xb5\xd1\x80\xd0\xb8\xd1\x82\xd0\xb5 \xd1\x83\xd0\xbd\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x80\xd1\x81\xd0\xb8\xd1\x82\xd0\xb5\xd1\x82\xd1\x8b'),
        ),
    ]
