# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20171109_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=b'Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name=b'Title')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name=b'Title')),
                ('reg_file', models.FileField(upload_to=b'files/regulation', verbose_name=b'File')),
                ('reg_file_en', models.FileField(null=True, upload_to=b'files/regulation', verbose_name=b'File')),
                ('reg_file_tr', models.FileField(null=True, upload_to=b'files/regulation', verbose_name=b'File')),
            ],
            options={
                'verbose_name': 'object',
                'verbose_name_plural': 'Regulation',
            },
        ),
        migrations.AlterField(
            model_name='mainuniversity',
            name='university',
            field=models.ManyToManyField(max_length=20, related_name='country_university', to='main.University', verbose_name=b'\xd0\x92\xd1\x8b\xd0\xb1\xd0\xb5\xd1\x80\xd0\xb8\xd1\x82\xd0\xb5 \xd1\x83\xd0\xbd\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x80\xd1\x81\xd0\xb8\xd1\x82\xd0\xb5\xd1\x82\xd1\x8b'),
        ),
    ]
